spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beneficios
    driver-class-name: org.postgresql.Driver
    username: bip
    password: bip@123
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
