spring:
  datasource:
    url: jdbc:h2:mem:beneficios;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always
  retry:
    enabled: true

server:
  port: 8082

cors:
  allowed-origins: http://localhost:4200

logging:
  level:
    root: INFO
    com.example: INFO
    org.springframework.retry: INFO
    org.springframework.web.servlet.DispatcherServlet: WARN
    org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
