CREATE TABLE IF NOT EXISTS BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  CNPJ VARCHAR(32),
  VALOR DECIMAL(15,2) NOT NULL,
  ATIVO BOOLEAN DEFAULT TRUE,
  CREATED_BY VARCHAR(50),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(50),
  UPDATED_AT TIMESTAMP,
  VERSION BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS IDEMPOTENCIA (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CHAVE VARCHAR(255) NOT NULL UNIQUE,
  RESULTADO TEXT,
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EXPIRE_EM TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
  ATIVO BOOLEAN DEFAULT TRUE,
  VERSION BIGINT DEFAULT 0 NOT NULL
);
